"""Initial migration: Create board system tables

Revision ID: 957906efcfec
Revises: 
Create Date: 2025-12-01 03:05:58.716835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957906efcfec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('card_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'position', name='uq_board_list_position')
    )
    op.create_index('idx_list_board_position', 'board_lists', ['board_id', 'position'], unique=False)
    op.create_index(op.f('ix_board_lists_board_id'), 'board_lists', ['board_id'], unique=False)
    op.create_table('boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('members', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('admins', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DELETED', name='boardstatus'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'TEAM', 'ORGANIZATION', 'PUBLIC', name='boardvisibility'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priority'), nullable=False),
    sa.Column('enable_comments', sa.Boolean(), nullable=False),
    sa.Column('enable_attachments', sa.Boolean(), nullable=False),
    sa.Column('enable_due_dates', sa.Boolean(), nullable=False),
    sa.Column('enable_labels', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_board_company_status', 'boards', ['company_id', 'status'], unique=False)
    op.create_index('idx_board_owner_created', 'boards', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_boards_branch_id'), 'boards', ['branch_id'], unique=False)
    op.create_index(op.f('ix_boards_company_id'), 'boards', ['company_id'], unique=False)
    op.create_index(op.f('ix_boards_created_at'), 'boards', ['created_at'], unique=False)
    op.create_index(op.f('ix_boards_deleted_at'), 'boards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_boards_department_id'), 'boards', ['department_id'], unique=False)
    op.create_index(op.f('ix_boards_name'), 'boards', ['name'], unique=False)
    op.create_index(op.f('ix_boards_owner_id'), 'boards', ['owner_id'], unique=False)
    op.create_index(op.f('ix_boards_status'), 'boards', ['status'], unique=False)
    op.create_index(op.f('ix_boards_team_id'), 'boards', ['team_id'], unique=False)
    op.create_table('card_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachment_card_uploaded', 'card_attachments', ['card_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_card_attachments_card_id'), 'card_attachments', ['card_id'], unique=False)
    op.create_table('card_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_card_created', 'card_comments', ['card_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_card_comments_author_id'), 'card_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_card_comments_card_id'), 'card_comments', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_comments_created_at'), 'card_comments', ['created_at'], unique=False)
    op.create_table('card_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'label_id', name='uq_card_label')
    )
    op.create_index('idx_card_label_card', 'card_labels', ['card_id'], unique=False)
    op.create_index('idx_card_label_label', 'card_labels', ['label_id'], unique=False)
    op.create_index(op.f('ix_card_labels_card_id'), 'card_labels', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_labels_label_id'), 'card_labels', ['label_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('watchers', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED', name='cardstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priority'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('checklist_items', sa.Integer(), nullable=False),
    sa.Column('checklist_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'position', name='uq_card_list_position')
    )
    op.create_index('idx_card_assignee_status', 'cards', ['assignee_id', 'status'], unique=False)
    op.create_index('idx_card_due_date', 'cards', ['due_date'], unique=False)
    op.create_index(op.f('ix_cards_assignee_id'), 'cards', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_cards_created_at'), 'cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_cards_due_date'), 'cards', ['due_date'], unique=False)
    op.create_index(op.f('ix_cards_list_id'), 'cards', ['list_id'], unique=False)
    op.create_index(op.f('ix_cards_reporter_id'), 'cards', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_cards_title'), 'cards', ['title'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'name', name='uq_board_label_name')
    )
    op.create_index(op.f('ix_labels_board_id'), 'labels', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_board_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_cards_title'), table_name='cards')
    op.drop_index(op.f('ix_cards_reporter_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_list_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_due_date'), table_name='cards')
    op.drop_index(op.f('ix_cards_created_at'), table_name='cards')
    op.drop_index(op.f('ix_cards_assignee_id'), table_name='cards')
    op.drop_index('idx_card_due_date', table_name='cards')
    op.drop_index('idx_card_assignee_status', table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_card_labels_label_id'), table_name='card_labels')
    op.drop_index(op.f('ix_card_labels_card_id'), table_name='card_labels')
    op.drop_index('idx_card_label_label', table_name='card_labels')
    op.drop_index('idx_card_label_card', table_name='card_labels')
    op.drop_table('card_labels')
    op.drop_index(op.f('ix_card_comments_created_at'), table_name='card_comments')
    op.drop_index(op.f('ix_card_comments_card_id'), table_name='card_comments')
    op.drop_index(op.f('ix_card_comments_author_id'), table_name='card_comments')
    op.drop_index('idx_comment_card_created', table_name='card_comments')
    op.drop_table('card_comments')
    op.drop_index(op.f('ix_card_attachments_card_id'), table_name='card_attachments')
    op.drop_index('idx_attachment_card_uploaded', table_name='card_attachments')
    op.drop_table('card_attachments')
    op.drop_index(op.f('ix_boards_team_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_status'), table_name='boards')
    op.drop_index(op.f('ix_boards_owner_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_name'), table_name='boards')
    op.drop_index(op.f('ix_boards_department_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_deleted_at'), table_name='boards')
    op.drop_index(op.f('ix_boards_created_at'), table_name='boards')
    op.drop_index(op.f('ix_boards_company_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_branch_id'), table_name='boards')
    op.drop_index('idx_board_owner_created', table_name='boards')
    op.drop_index('idx_board_company_status', table_name='boards')
    op.drop_table('boards')
    op.drop_index(op.f('ix_board_lists_board_id'), table_name='board_lists')
    op.drop_index('idx_list_board_position', table_name='board_lists')
    op.drop_table('board_lists')
    # ### end Alembic commands ###
