"""createdat and updated at added

Revision ID: ded7554d938d
Revises: 957906efcfec
Create Date: 2025-12-01 11:49:46.265451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ded7554d938d'
down_revision: Union[str, Sequence[str], None] = '957906efcfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_lists', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('board_lists', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('board_lists', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_board_lists_created_at'), 'board_lists', ['created_at'], unique=False)
    op.create_index(op.f('ix_board_lists_created_by'), 'board_lists', ['created_by'], unique=False)
    op.create_index(op.f('ix_board_lists_deleted_at'), 'board_lists', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_board_lists_deleted_by'), 'board_lists', ['deleted_by'], unique=False)
    op.add_column('boards', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('boards', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_boards_created_by'), 'boards', ['created_by'], unique=False)
    op.create_index(op.f('ix_boards_deleted_by'), 'boards', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_boards_id'), 'boards', ['id'], unique=False)
    op.add_column('card_attachments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('card_attachments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('card_attachments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('card_attachments', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('card_attachments', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_attachment_card_uploaded'), table_name='card_attachments')
    op.create_index('idx_attachment_card_uploaded', 'card_attachments', ['card_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_card_attachments_created_at'), 'card_attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_card_attachments_created_by'), 'card_attachments', ['created_by'], unique=False)
    op.create_index(op.f('ix_card_attachments_deleted_at'), 'card_attachments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_card_attachments_deleted_by'), 'card_attachments', ['deleted_by'], unique=False)
    op.drop_column('card_attachments', 'uploaded_at')
    op.add_column('card_comments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('card_comments', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('card_comments', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_card_comments_created_by'), 'card_comments', ['created_by'], unique=False)
    op.create_index(op.f('ix_card_comments_deleted_at'), 'card_comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_card_comments_deleted_by'), 'card_comments', ['deleted_by'], unique=False)
    op.add_column('card_labels', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('card_labels', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('card_labels', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('card_labels', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_card_labels_created_at'), 'card_labels', ['created_at'], unique=False)
    op.create_index(op.f('ix_card_labels_created_by'), 'card_labels', ['created_by'], unique=False)
    op.create_index(op.f('ix_card_labels_deleted_at'), 'card_labels', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_card_labels_deleted_by'), 'card_labels', ['deleted_by'], unique=False)
    op.add_column('cards', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('cards', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cards_archived_at'), 'cards', ['archived_at'], unique=False)
    op.create_index(op.f('ix_cards_created_by'), 'cards', ['created_by'], unique=False)
    op.create_index(op.f('ix_cards_deleted_at'), 'cards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cards_deleted_by'), 'cards', ['deleted_by'], unique=False)
    op.add_column('labels', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('labels', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('labels', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('labels', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_labels_created_at'), 'labels', ['created_at'], unique=False)
    op.create_index(op.f('ix_labels_created_by'), 'labels', ['created_by'], unique=False)
    op.create_index(op.f('ix_labels_deleted_at'), 'labels', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_labels_deleted_by'), 'labels', ['deleted_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_deleted_by'), table_name='labels')
    op.drop_index(op.f('ix_labels_deleted_at'), table_name='labels')
    op.drop_index(op.f('ix_labels_created_by'), table_name='labels')
    op.drop_index(op.f('ix_labels_created_at'), table_name='labels')
    op.drop_column('labels', 'deleted_by')
    op.drop_column('labels', 'created_by')
    op.drop_column('labels', 'deleted_at')
    op.drop_column('labels', 'updated_at')
    op.drop_index(op.f('ix_cards_deleted_by'), table_name='cards')
    op.drop_index(op.f('ix_cards_deleted_at'), table_name='cards')
    op.drop_index(op.f('ix_cards_created_by'), table_name='cards')
    op.drop_index(op.f('ix_cards_archived_at'), table_name='cards')
    op.drop_column('cards', 'deleted_by')
    op.drop_column('cards', 'created_by')
    op.drop_column('cards', 'deleted_at')
    op.drop_index(op.f('ix_card_labels_deleted_by'), table_name='card_labels')
    op.drop_index(op.f('ix_card_labels_deleted_at'), table_name='card_labels')
    op.drop_index(op.f('ix_card_labels_created_by'), table_name='card_labels')
    op.drop_index(op.f('ix_card_labels_created_at'), table_name='card_labels')
    op.drop_column('card_labels', 'deleted_by')
    op.drop_column('card_labels', 'created_by')
    op.drop_column('card_labels', 'deleted_at')
    op.drop_column('card_labels', 'updated_at')
    op.drop_index(op.f('ix_card_comments_deleted_by'), table_name='card_comments')
    op.drop_index(op.f('ix_card_comments_deleted_at'), table_name='card_comments')
    op.drop_index(op.f('ix_card_comments_created_by'), table_name='card_comments')
    op.drop_column('card_comments', 'deleted_by')
    op.drop_column('card_comments', 'created_by')
    op.drop_column('card_comments', 'deleted_at')
    op.add_column('card_attachments', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_card_attachments_deleted_by'), table_name='card_attachments')
    op.drop_index(op.f('ix_card_attachments_deleted_at'), table_name='card_attachments')
    op.drop_index(op.f('ix_card_attachments_created_by'), table_name='card_attachments')
    op.drop_index(op.f('ix_card_attachments_created_at'), table_name='card_attachments')
    op.drop_index('idx_attachment_card_uploaded', table_name='card_attachments')
    op.create_index(op.f('idx_attachment_card_uploaded'), 'card_attachments', ['card_id', 'uploaded_at'], unique=False)
    op.drop_column('card_attachments', 'deleted_by')
    op.drop_column('card_attachments', 'created_by')
    op.drop_column('card_attachments', 'deleted_at')
    op.drop_column('card_attachments', 'updated_at')
    op.drop_column('card_attachments', 'created_at')
    op.drop_index(op.f('ix_boards_id'), table_name='boards')
    op.drop_index(op.f('ix_boards_deleted_by'), table_name='boards')
    op.drop_index(op.f('ix_boards_created_by'), table_name='boards')
    op.drop_column('boards', 'deleted_by')
    op.drop_column('boards', 'created_by')
    op.drop_index(op.f('ix_board_lists_deleted_by'), table_name='board_lists')
    op.drop_index(op.f('ix_board_lists_deleted_at'), table_name='board_lists')
    op.drop_index(op.f('ix_board_lists_created_by'), table_name='board_lists')
    op.drop_index(op.f('ix_board_lists_created_at'), table_name='board_lists')
    op.drop_column('board_lists', 'deleted_by')
    op.drop_column('board_lists', 'created_by')
    op.drop_column('board_lists', 'deleted_at')
    # ### end Alembic commands ###
